config/routes.rb
Rails.application.routes.draw do
  
  resources :contactos

  resources :lugar_nacimientos

  resources :roles

  devise_for :users
  resources :estado_civils

  resources :departamentos

  resources :users

  resources :dato_estudiantes do
    get :autocomplete_municipio_nombre, :on => :collection
  end

  resources :municipios

  resources :pais

  resources :tipo_documentos

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  
  
  get 'static_pages/usuarios'
  get 'static_pages/registros'
  get 'static_pages/reportes'
  get 'static_pages/configuracion'
  get 'static_pages/consulta'

  
  
  get 'static_pages/olvidaste_password'
 
  get 'static_pages/registrarse'
 
  get 'static_pages/registro_asistencia'

  get 'static_pages/registro_horarios'
 
  get'static_pages/registros_grados'
 
  get'static_pages/registros_grados'

  get'static_pages/reportes_alumnos'

  get'static_pages/reportes_jornadas'
  
  get 'static_pages/reportes_asistencia'
 
  get'static_pages/configuracion_user'

  get'static_pages/configuracion_preferencias'
 
  get'static_pages/agregar_info'
  
  get'static_pages/consultar_usuarios'
  
  get'static_pages/configurar_grupos'
  
  get'static_pages/consultar_alumnos'
  
  get'static_pages/consultar_jornadas'
  
  match '/home', to: 'static_pages#home',  via: 'get'
  match '/help',	to: 'static_pages#help',  via: 'get'
  match '/about',   to: 'static_pages#about',  via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'
  
  match '/usuarios', to: 'static_pages#usuarios',  via: 'get'
  match '/registros', to: 'static_pages#registros',  via: 'get'
  match '/reportes', to: 'static_pages#reportes',  via: 'get'
  match '/configuracion', to: 'static_pages#configuracion',  via: 'get'
  match '/consulta', to: 'static_pages#consulta',  via: 'get'
  
  match '/olvidaste_password', to: 'static_pages#olvidaste_password',  via: 'get'
  match '/registrarse', to: 'static_pages#registrarse',  via: 'get'
  match '/registro_asistencia', to: 'static_pages#registro_asistencia',  via: 'get'
  match '/registro_horarios', to: 'static_pages#registro_horarios',  via: 'get'
  match '/registros_grados', to: 'static_pages#registros_grados',  via: 'get'
  match '/reportes_asistencia', to: 'static_pages#reportes_asistencia',  via: 'get'
  match '/reportes_alumnos', to: 'static_pages#reportes_alumnos',  via: 'get'
  match '/reportes_jornadas', to: 'static_pages#reportes_jornadas',  via: 'get'
  match '/configuracion_user', to: 'static_pages#configuracion_user',  via: 'get'
  match '/configuracion_preferencias', to: 'static_pages#configuracion_preferencias',  via: 'get'
  match '/agregar_info', to: 'static_pages#agregar_info',  via: 'get'
  match '/consultar_usuarios', to: 'static_pages#consultar_usuarios',  via: 'get'
  match '/consultar_jornadas', to: 'static_pages#consultar_jornadas',  via: 'get'
  match '/consultar_configuracion', to: 'static_pages#consultar_configuracion',  via: 'get'
  match '/consultar_alumnos', to: 'static_pages#consultar_alumnos',  via: 'get'
  match '/configurar_grupos', to: 'static_pages#configurar_grupos',  via: 'get'
  match '/ver', to: 'static_pages#ver',  via: 'get'
  match '/v2', to: 'static_pages#v2',  via: 'get'
  match '/v3', to: 'static_pages#v3',  via: 'get'
  match '/pais', to: 'static_pages#pais',  via: 'get'
 

  root :to => 'static_pages#home'

end

app/models/dato_estudiante.rb
class DatoEstudiante < ActiveRecord::Base
  belongs_to :pais
  belongs_to :municipio
  belongs_to :departamento
  
  
  # Validar que los atributos sean obligatorios
  validates :codigo, :presence => true
  validates :nombre, :presence => true
  validates :apellido, :presence => true
  validates :mail, :presence => true
  validates :doc_identidad, :presence => true
  validates :curso, :presence => true
  validates :grado, :presence => true
  validates :pais, :presence => true
  validates :municipio, :presence => true
  validates :departamento, :presence => true
  validates :telefono, :presence => true
  validates :celular, :presence => true
  validates :direccion, :presence => true
  validates :fch_nacimiento, :presence => true
  validates :tipo_doc, :presence => true
  
  
  # validar un atributo booleano
  validates :genero, inclusion: [true, false]
  
  # validar que un atributos unicos
  validates :codigo, uniqueness: { message: "No se puede Repetir" }
  validates :nombre, uniqueness: { message: "No se puede Repetir" }
  
  # validar formato de un email
  validates :mail, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
  message: 'Formato no valido' }
  
  # valida la longitud de un campo, tanto la longitud minima como la maxima
  validates :doc_identidad, length: { minimum: 5, maximum: 30 }
  validates :nombre, length: { minimum: 5, maximum: 50 }
  
  # Valida si un atributo es numerico
  validates :codigo, numericality: true
  validates :telefono, :presence => true
  
  
  
  def self.search(search, page)
      where(['upper(codigo) like ?', "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("codigo")
  end
  
  

end

app/controllers/dato_estudiantes_controller.rb
class  DatoEstudiantesController  < ApplicationController
 
  before_action :set_dato_estudiante, only: [:show, :edit, :update, :destroy]
  autocomplete :municipio, :nombre


  def index
      @dato_estudiantes = DatoEstudiante.search(params[:search], params[:page])
  end

  def show
  end

  def new
        @dato_estudiante = DatoEstudiante.new
  end

  def edit
  end

  def create
       @dato_estudiante = DatoEstudiante.new
       @dato_estudiante.municipio_id = params[:id_municipio]
       render action: :new unless @dato_estudiante.save
  end

  def update
        render action: :edit unless @dato_estudiante.update_attributes(dato_estudiante_params)
  end

  def destroy
       @dato_estudiante.destroy
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dato_estudiante
       @dato_estudiante = DatoEstudiante.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dato_estudiante_params
        params.require(:dato_estudiante).permit(:codigo, :nombre, :apellido, :fch_nacimiento, :mail, :tipo_doc, :doc_identidad, :curso, :grado, :pais_id, :municipio_id, :direccion, :telefono, :celular, :genero, :departamento)
  end

end

app/helpers/dato_estudiantes_helper.rb
module DatoEstudiantesHelper
    
  def mostrar_genero(genero)
      if genero
          "Masculino"
      else
          "Femenino"
      end
  end
  
  def calcular_edad(fch_nacimiento)
      now = Date.today
      year = now.year - fch.year
  end
  
end

app/views/dato_estudiantes/_dato_estudiante.html.erb
<tr id=<%= "dato_estudiante_#{dato_estudiante.id}" %>>
        <td><%= dato_estudiante.codigo %></td>
        <td><%= dato_estudiante.nombre %></td>
        <td><%= dato_estudiante.apellido %></td>
        <td><%= dato_estudiante.fch_nacimiento %></td>
        <td><%= calcular_edad(dato_estudiante.fch_nacimiento) %></td>
        <td><%= dato_estudiante.mail %></td>
        <td><%= dato_estudiante.doc_identidad %></td>
        <td><%= dato_estudiante.tipo_doc %></td>
        <td><%= dato_estudiante.curso %></td>
        <td><%= dato_estudiante.grado %></td>
        <td><%= dato_estudiante.pais.nombre %></td>
        <td><%= dato_estudiante.departamento.nombre %></td>
        <td><%= dato_estudiante.municipio.nombre %></td>
        <td><%= dato_estudiante.direccion %></td>
        <td><%= dato_estudiante.telefono %></td>
        <td><%= dato_estudiante.celular  %></td>
        <td><%= mostrar_genero(dato_estudiante.genero) %></td>
        <td><%= link_to 'Mostrar', dato_estudiante, remote: true, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_dato_estudiante_path(dato_estudiante), remote: true, class="btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', dato_estudiante, method: :delete, remote :true,  data: { confirm: 'Estas Seguro?' }, remote: true, class: "btn btn-danger" %></td>
</tr> 

app/views/dato_estudiantes/_form.html.erb
<%= simple_form_for(@dato_estudiante, :html => { :class => 'form-horizontal', remote: true } ) do |f| %>

  <% if @dato_estudiante.errors.any? %>
	<div id="error_explanation">
  	<h2 class="alert alert-dismissible alert-success"><%= pluralize(@dato_estudiante.errors.count, "error") %> prohibited this municipio from being saved:</h2>

  	<ul>
  	<% @dato_estudiante.errors.full_messages.each do |message| %>
    	<li><%= message %></li>
  	<% end %>
  	</ul>
	</div>
  <% end %>
  
  <br>
  
  <br>
  
  <br>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Panel success</h3>
  </div>
  <div class="panel-body">
<div class="form-group has-success">
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Codigo</label>
   	<div class="col-md-4">
      	<%= f.input_field :codigo, class: 'form-control', placeholder: "Codigo" %>
   	</div>
  </div>
  </div>
 
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Nombre</label>
   	<div class="col-md-4">
      	<%= f.input_field :nombre, class: 'form-control', placeholder: "Nombre" %>
   	</div>
  </div>
  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Apellido</label>
   	<div class="col-md-4">
      	<%= f.input_field :apellido, class: 'form-control', placeholder: "Apellido" %>
   	</div>
  </div>
  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Correo electronico</label>
   	<div class="col-md-4">
      	<%= f.input_field :mail, class: 'form-control', placeholder: "Email" %>
   	</div>
  </div>

  
 
   <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Tipo documento</label>
   	<div class="col-md-4">
      	<%= f.collection_select :pais_id, TipoDocumento.all, :id, :nombre, prompt: "Seleccione tipo documento", class: "form-control" %>
   	</div>
  </div>
  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Documento identidad</label>
   	<div class="col-md-4">
      	<%= f.input_field :doc_identidad , class: 'form-control', placeholder: "Identidad" %>
   	</div>
  </div>
  
  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Fecha nacimiento</label>
   	<div class="col-md-4">
   	  <%= f.text_field :fch_nacimiento, 'data-provide' => "datepicker", class: "form-control", size: "40", width: "20", heigth: "62" %>
   	</div>
  </div>

  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Curso</label>
   	<div class="col-md-4">
      	<%= f.input_field :curso, class: 'form-control', placeholder: "Curso" %>
   	</div>
  </div>



  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Grado</label>
   	<div class="col-md-4">
      	<%= f.input_field :grado, class: 'form-control', placeholder: "Grado" %>
   	</div>
  </div>
  

  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Pais</label>
   	<div class="col-md-4">
        <%= f.collection_select :pais_id, Pai.all, :id, :nombre, class: "form-control lg-6", prompt: "Seleccione Pais" %>
   	</div>
  </div>

  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Municipio</label>
   	<div class="col-md-4">
        <%= f.collection_select :municipio_id, Municipio.all, :id, :nombre, class: 'form-control lg-6', prompt: "Seleccione Municipio" %>
   	</div>
  </div>
  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">direccion</label>
   	<div class="col-md-4">
       	<%= f.input_field :direccion, class: 'form-control', placeholder: "direccion" %>
   	</div>
  </div>

  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">telefono</label>
   	<div class="col-md-4">
      	<%= f.input_field :telefono, class: 'form-control', placeholder: "telefono" %>
   	</div>
  </div>
  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Celular</label>
   	<div class="col-md-4">
      	<%= f.input_field :celular, class: 'form-control', placeholder: "celular" %>
   	</div>
  </div>
  
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label-left">Genero</label>
   	<div class="col-md-4">
      	Masculino: <%= f.radio_button(:genero, true) %>
        Femenino: <%= f.radio_button(:genero, false) %>
   	</div>
  </div>

  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
  	<%= f.submit "Guardar", class: "btn btn-sm btn-success" %>
	</div>
  </div>

<% end %>

  </div>
</div>

app/views/dato_estudiantes/_show.html.erb
<div class='dato_estudiante'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @dato_estudiante.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @dato_estudiante.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @dato_estudiante.apellido %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @dato_estudiante.fch_nacimiento %>
</p>

<p>
  <strong>Edad:</strong>
  <%= calcular_edad(@dato_estudiante.fch_nacimiento) %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @dato_estudiante.mail %>
</p>

<p>
  <strong>Doc identidad:</strong>
  <%= @dato_estudiante.doc_identidad %>
</p>

<p>
  <strong>Doc identidad:</strong>
  <%= @dato_estudiante.tipo_doc %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @dato_estudiante.curso %>
</p>

<p>
  <strong>Grado:</strong>
  <%= @dato_estudiante.grado %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @dato_estudiante.pais %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @dato_estudiante.departamento %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @dato_estudiante.municipio.nombre rescue nil %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @dato_estudiante.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @dato_estudiante.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @dato_estudiante.celular %>
</p>

<p>
  <strong>Genero:</strong>
  <%= mostrar_genero(@dato_estudiante.genero) %>
</p>

<%= link_to 'Editar', edit_dato_estudiante_path(@dato_estudiante) %> |
<%= link_to 'Atras', dato_estudiantes_path %>
</div>

app/views/dato_estudiantes/create.js.erb
$('table tbody').append("<%= escape_javascript(render @dato_estudiante) %>")
$.lazybox.close()

app/views/dato_estudiantes/destroy.js.erb
$.lazybox.close()
$("table tr#dato_estudiante_<%= @dato_estudiante.id %>").remove();

app/views/dato_estudiantes/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {klass: 'custom'});

app/views/dato_estudiantes/index.html.erb
<h1>Listado de estudiantes</h1>


<div class="container">
    
  <div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Panel success</h3>
  </div>
  <div class="panel-body">

<%= form_tag dato_estudiantes_path, :method => 'get' do %>
     <% content_tag :label do %>
        <h5 class="bus">Buscar:</h5>
        <%= autocomplete_field_tag 'doc_identidad', '', autocomplete_municipio_nombre_dato_estudiantes_path, :size => 75, id: "inp1", placeholder: "codigo", class: "form-control lg-6" %>
     <% end %>
<% end %>

<button class="btn btn-success btn-sm" name="nil", id="btn-1">
    <%= image_tag("search.png") %>
</button>

<br>
    </div>
</div>

<br>


<div class="panel panel-success">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Importar Datos Ocultar/Mostrar
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>fecha</th>
      <th>Edad</th>
      <th>Mail</th>
      <th>Tipo</th>
      <th>documento</th>
      <th>Curso</th>
      <th>Grado</th>
      <th>Pais</th>
      <th>Municipio</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Celular</th>
      <th>Genero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <%= render @dato_estudiantes %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Alumno', new_dato_estudiante_path, remote: true, class: "btn btn-info" %>

<%= will_paginate @dato_estudiantes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Alumnos: <%= @dato_estudiantes.count %>
    
    </div>
  </div>
</div>
     

app/views/dato_estudiantes/new.js.erb
$.lazybox("<%= j(render partial: 'form') %>", { onTop: false });

app/views/dato_estudiantes/show.js.erb
$.lazybox("<%= j(render 'show') %>", { closeImg: true, klass: 'sticker' })

app/views/dato_estudiantes/update.js.erb
$('tr#dato_estudiante_<%= @dato_estudiante.id %>').replaceWith("<%= escape_javascript(render @dato_estudiante) %>")
$.lazybox.close()