config/routes.rb
Rails.application.routes.draw do
  
  resources :contactos

  resources :lugar_nacimientos

  resources :roles

  devise_for :users
  resources :estado_civils

  resources :departamentos

  resources :users

  resources :dato_estudiantes do
    get :autocomplete_municipio_nombre, :on => :collection
  end

  resources :municipios

  resources :pais

  resources :tipo_documentos

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  
  
  get 'static_pages/usuarios'
  get 'static_pages/registros'
  get 'static_pages/reportes'
  get 'static_pages/configuracion'
  get 'static_pages/consulta'

  
  
  get 'static_pages/olvidaste_password'
 
  get 'static_pages/registrarse'
 
  get 'static_pages/registro_asistencia'

  get 'static_pages/registro_horarios'
 
  get'static_pages/registros_grados'
 
  get'static_pages/registros_grados'

  get'static_pages/reportes_alumnos'

  get'static_pages/reportes_jornadas'
  
  get 'static_pages/reportes_asistencia'
 
  get'static_pages/configuracion_user'

  get'static_pages/configuracion_preferencias'
 
  get'static_pages/agregar_info'
  
  get'static_pages/consultar_usuarios'
  
  get'static_pages/configurar_grupos'
  
  get'static_pages/consultar_alumnos'
  
  get'static_pages/consultar_jornadas'
  
  match '/home', to: 'static_pages#home',  via: 'get'
  match '/help',	to: 'static_pages#help',  via: 'get'
  match '/about',   to: 'static_pages#about',  via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'
  
  match '/usuarios', to: 'static_pages#usuarios',  via: 'get'
  match '/registros', to: 'static_pages#registros',  via: 'get'
  match '/reportes', to: 'static_pages#reportes',  via: 'get'
  match '/configuracion', to: 'static_pages#configuracion',  via: 'get'
  match '/consulta', to: 'static_pages#consulta',  via: 'get'
  
  match '/olvidaste_password', to: 'static_pages#olvidaste_password',  via: 'get'
  match '/registrarse', to: 'static_pages#registrarse',  via: 'get'
  match '/registro_asistencia', to: 'static_pages#registro_asistencia',  via: 'get'
  match '/registro_horarios', to: 'static_pages#registro_horarios',  via: 'get'
  match '/registros_grados', to: 'static_pages#registros_grados',  via: 'get'
  match '/reportes_asistencia', to: 'static_pages#reportes_asistencia',  via: 'get'
  match '/reportes_alumnos', to: 'static_pages#reportes_alumnos',  via: 'get'
  match '/reportes_jornadas', to: 'static_pages#reportes_jornadas',  via: 'get'
  match '/configuracion_user', to: 'static_pages#configuracion_user',  via: 'get'
  match '/configuracion_preferencias', to: 'static_pages#configuracion_preferencias',  via: 'get'
  match '/agregar_info', to: 'static_pages#agregar_info',  via: 'get'
  match '/consultar_usuarios', to: 'static_pages#consultar_usuarios',  via: 'get'
  match '/consultar_jornadas', to: 'static_pages#consultar_jornadas',  via: 'get'
  match '/consultar_configuracion', to: 'static_pages#consultar_configuracion',  via: 'get'
  match '/consultar_alumnos', to: 'static_pages#consultar_alumnos',  via: 'get'
  match '/configurar_grupos', to: 'static_pages#configurar_grupos',  via: 'get'
  match '/ver', to: 'static_pages#ver',  via: 'get'
  match '/v2', to: 'static_pages#v2',  via: 'get'
  match '/v3', to: 'static_pages#v3',  via: 'get'
  match '/pais', to: 'static_pages#pais',  via: 'get'
 

  root :to => 'static_pages#home'

end

app/models/lugar_nacimiento.rb
class LugarNacimiento < ActiveRecord::Base
end

app/controllers/lugar_nacimientos_controller.rb
class LugarNacimientosController < ApplicationController
  before_action :set_lugar_nacimiento, only: [:show, :edit, :update, :destroy]

  # GET /lugar_nacimientos
  # GET /lugar_nacimientos.json
  def index
    @lugar_nacimientos = LugarNacimiento.all
  end

  # GET /lugar_nacimientos/1
  # GET /lugar_nacimientos/1.json
  def show
  end

  # GET /lugar_nacimientos/new
  def new
    @lugar_nacimiento = LugarNacimiento.new
  end

  # GET /lugar_nacimientos/1/edit
  def edit
  end

  # POST /lugar_nacimientos
  # POST /lugar_nacimientos.json
  def create
    @lugar_nacimiento = LugarNacimiento.new(lugar_nacimiento_params)

    respond_to do |format|
      if @lugar_nacimiento.save
        format.html { redirect_to @lugar_nacimiento, notice: 'Lugar nacimiento was successfully created.' }
        format.json { render :show, status: :created, location: @lugar_nacimiento }
      else
        format.html { render :new }
        format.json { render json: @lugar_nacimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lugar_nacimientos/1
  # PATCH/PUT /lugar_nacimientos/1.json
  def update
    respond_to do |format|
      if @lugar_nacimiento.update(lugar_nacimiento_params)
        format.html { redirect_to @lugar_nacimiento, notice: 'Lugar nacimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @lugar_nacimiento }
      else
        format.html { render :edit }
        format.json { render json: @lugar_nacimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lugar_nacimientos/1
  # DELETE /lugar_nacimientos/1.json
  def destroy
    @lugar_nacimiento.destroy
    respond_to do |format|
      format.html { redirect_to lugar_nacimientos_url, notice: 'Lugar nacimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lugar_nacimiento
      @lugar_nacimiento = LugarNacimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lugar_nacimiento_params
      params.require(:lugar_nacimiento).permit(:nombre_departamento, :nombre_municipio, :nombre_centro_poblado, :nombre)
    end
end

app/helpers/lugar_nacimientos_helper.rb
module LugarNacimientosHelper
end

app/views/lugar_nacimientos/_form.html.erb
<%= simple_form_for(@lugar_nacimiento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre_departamento %>
    <%= f.input :nombre_municipio %>
    <%= f.input :nombre_centro_poblado %>
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lugar_nacimientos/edit.html.erb
<h1>Editing Lugar Nacimiento</h1>

<%= render 'form' %>

<%= link_to 'Show', @lugar_nacimiento %> |
<%= link_to 'Back', lugar_nacimientos_path %>

app/views/lugar_nacimientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lugar Nacimientos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre departamento</th>
      <th>Nombre municipio</th>
      <th>Nombre centro poblado</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lugar_nacimientos.each do |lugar_nacimiento| %>
      <tr>
        <td><%= lugar_nacimiento.nombre_departamento %></td>
        <td><%= lugar_nacimiento.nombre_municipio %></td>
        <td><%= lugar_nacimiento.nombre_centro_poblado %></td>
        <td><%= lugar_nacimiento.nombre %></td>
        <td><%= link_to 'Show', lugar_nacimiento %></td>
        <td><%= link_to 'Edit', edit_lugar_nacimiento_path(lugar_nacimiento) %></td>
        <td><%= link_to 'Destroy', lugar_nacimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lugar nacimiento', new_lugar_nacimiento_path %>

app/views/lugar_nacimientos/new.html.erb
<h1>New Lugar Nacimiento</h1>

<%= render 'form' %>

<%= link_to 'Back', lugar_nacimientos_path %>

app/views/lugar_nacimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre departamento:</strong>
  <%= @lugar_nacimiento.nombre_departamento %>
</p>

<p>
  <strong>Nombre municipio:</strong>
  <%= @lugar_nacimiento.nombre_municipio %>
</p>

<p>
  <strong>Nombre centro poblado:</strong>
  <%= @lugar_nacimiento.nombre_centro_poblado %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @lugar_nacimiento.nombre %>
</p>

<%= link_to 'Edit', edit_lugar_nacimiento_path(@lugar_nacimiento) %> |
<%= link_to 'Back', lugar_nacimientos_path %>