config/routes.rb
Rails.application.routes.draw do
  
  resources :contactos

  resources :lugar_nacimientos

  resources :roles

  devise_for :users
  resources :estado_civils

  resources :departamentos

  resources :users

  resources :dato_estudiantes do
    get :autocomplete_municipio_nombre, :on => :collection
  end

  resources :municipios

  resources :pais

  resources :tipo_documentos

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  
  
  get 'static_pages/usuarios'
  get 'static_pages/registros'
  get 'static_pages/reportes'
  get 'static_pages/configuracion'
  get 'static_pages/consulta'

  
  
  get 'static_pages/olvidaste_password'
 
  get 'static_pages/registrarse'
 
  get 'static_pages/registro_asistencia'

  get 'static_pages/registro_horarios'
 
  get'static_pages/registros_grados'
 
  get'static_pages/registros_grados'

  get'static_pages/reportes_alumnos'

  get'static_pages/reportes_jornadas'
  
  get 'static_pages/reportes_asistencia'
 
  get'static_pages/configuracion_user'

  get'static_pages/configuracion_preferencias'
 
  get'static_pages/agregar_info'
  
  get'static_pages/consultar_usuarios'
  
  get'static_pages/configurar_grupos'
  
  get'static_pages/consultar_alumnos'
  
  get'static_pages/consultar_jornadas'
  
  match '/home', to: 'static_pages#home',  via: 'get'
  match '/help',	to: 'static_pages#help',  via: 'get'
  match '/about',   to: 'static_pages#about',  via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'
  
  match '/usuarios', to: 'static_pages#usuarios',  via: 'get'
  match '/registros', to: 'static_pages#registros',  via: 'get'
  match '/reportes', to: 'static_pages#reportes',  via: 'get'
  match '/configuracion', to: 'static_pages#configuracion',  via: 'get'
  match '/consulta', to: 'static_pages#consulta',  via: 'get'
  
  match '/olvidaste_password', to: 'static_pages#olvidaste_password',  via: 'get'
  match '/registrarse', to: 'static_pages#registrarse',  via: 'get'
  match '/registro_asistencia', to: 'static_pages#registro_asistencia',  via: 'get'
  match '/registro_horarios', to: 'static_pages#registro_horarios',  via: 'get'
  match '/registros_grados', to: 'static_pages#registros_grados',  via: 'get'
  match '/reportes_asistencia', to: 'static_pages#reportes_asistencia',  via: 'get'
  match '/reportes_alumnos', to: 'static_pages#reportes_alumnos',  via: 'get'
  match '/reportes_jornadas', to: 'static_pages#reportes_jornadas',  via: 'get'
  match '/configuracion_user', to: 'static_pages#configuracion_user',  via: 'get'
  match '/configuracion_preferencias', to: 'static_pages#configuracion_preferencias',  via: 'get'
  match '/agregar_info', to: 'static_pages#agregar_info',  via: 'get'
  match '/consultar_usuarios', to: 'static_pages#consultar_usuarios',  via: 'get'
  match '/consultar_jornadas', to: 'static_pages#consultar_jornadas',  via: 'get'
  match '/consultar_configuracion', to: 'static_pages#consultar_configuracion',  via: 'get'
  match '/consultar_alumnos', to: 'static_pages#consultar_alumnos',  via: 'get'
  match '/configurar_grupos', to: 'static_pages#configurar_grupos',  via: 'get'
  match '/ver', to: 'static_pages#ver',  via: 'get'
  match '/v2', to: 'static_pages#v2',  via: 'get'
  match '/v3', to: 'static_pages#v3',  via: 'get'
  match '/pais', to: 'static_pages#pais',  via: 'get'
 

  root :to => 'static_pages#home'

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
    
    has_many :dato_estudiantes
    
    # Validar que los astributos sean obligatorios
    validates :nombre, :presence => true
    
    # valida la longitud de un campo, tanto la longitud minima como la maxima
    validates :nombre, length: { minimum: 5, maximum: 55 }
    
     # validar que un atributos unicos
    validates :nombre, uniqueness: { message: "No se puede Repetir" }
    
    def self.search(search, page)
        where(['upper(nombre) like ?', "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("nombre")
    end
    
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
 
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]
  

  def index
       
        @departamentos = Departamento.search(params[:search], params[:page])
  end

  def show
  end

  def new
        @departamento = Departamento.new
  end

  def edit
  end

  def create
       @departamento = Departamento.new(departamento_params)
       render action: :new unless @departamento.save
  end

  def update
        render action: :edit unless @departamento.update_attributes(departamento_params)
  end

  def destroy
       @departamento.destroys
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_departamento
       @departamento = Departamento.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def departamento_params
        params.require(:departamento).permit(:nombre)
  end

end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_departamento.html.erb
<tr id=<%= "departamento_#{departamento.id}" %>>
   <td><%= departamento.nombre %></td>
   <td><%= link_to 'Mostrar', departamento, remote: true, class: "btn btn-primary" %></td>
   <td><%= link_to 'Editar', edit_departamento_path(departamento), remote: true, class: "btn btn-success"  %></td>
   <td><%= link_to 'Eliminar', departamento, method: :delete, remote: true,  data: { confirm: 'Esta Seguro?' }, class: "btn btn-danger" %></td>
</tr>   

app/views/departamentos/_form.html.erb
<%= simple_form_for(@departamento, :html => { :class => 'form-horizontal', remote: true } ) do |f| %>

  <% if @departamento.errors.any? %>
	<div id="error_explanation">
  	<h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this municipio from being saved:</h2>

  	<ul>
  	<% @departamento.errors.full_messages.each do |message| %>
    	<li><%= message %></li>
  	<% end %>
  	</ul>
	</div>
  <% end %>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Crear nuevo departamento</h3>
  </div>
  <div class="panel-body">
  <div class="form-group">
   	<label for="name" class="col-sm-3 control-label">Nombre</label>
   	<div class="col-md-4">
      	<%= f.input_field :nombre, class: 'form-control' %>
   	</div>
  </div>

  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
  	<%= f.submit "Guardar", class: "btn btn-sm btn-success" %>
	</div>
  </div>
</div>
</div>

<% end %>

app/views/departamentos/_show.html.erb
<div class="departamentos">
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Informacion</h3>
  </div>
  <div class="panel-body">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @departamento.nombre %>
</p>

<%= link_to 'Editar', edit_departamento_path(@departamento), class: "btn btn-info btn-sm" %> |
<%= link_to 'Atras', departamentos_path, class: "btn btn-success btn-sm" %>
</div>
</div>
</div>

app/views/departamentos/create.js.erb
$('table tbody').append("<%= escape_javascript(render @departamento) %>")
$.lazybox.close()

app/views/departamentos/destroy.js.erb
$.lazybox.close()
$("table tr#departamento_<%= @departamento.id %>").remove();

app/views/departamentos/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {klass: 'custom'});

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Busqueda </h3>
  </div>
  <div class="panel-body">
      
      <br>
    <%= form_tag departamentos_path, :method => 'get' do %>
     <% content_tag :label do %>
          <h5 class="bus2">Buscar:</h5>
         <%= text_field_tag :search, params[:search], id: "inp12", placeholder: "nombres", class: 'form-control lg-6' %>
     <% end %>
    <% end %>

    <button class="btn btn-info btn-sm" name="nil", id="btn-11">
        <%= image_tag("search.png") %>
    </button>
    
    <br>
  
  </div>
</div>

<br>

<br>

<br>


<h1>Listado de departamentos</h1>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">mostrar datos</h3>
  </div>
  <div class="panel-body">
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= render @departamentos %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo departamento', new_departamento_path, remote: true, class: "btn btn-info" %>

<br>

<br>
departamento: <%= @departamentos.count %>

<br>
<%= will_paginate @departamentos, renderer: BootstrapPagination::Rails, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;', class: 'pagination pagination-sm', id: 'pag-1' %>
</div>
</div>
</div>

app/views/departamentos/new.js.erb
$.lazybox("<%= j(render partial: 'form') %>", { onTop: false });

app/views/departamentos/show.js.erb
$.lazybox("<%= j(render 'show') %>", { closeImg: true, klass: 'sticker' })

app/views/departamentos/update.js.erb
$('tr#departamento_<%= @departamento.id %>').replaceWith("<%= escape_javascript(render @departamento) %>")
$.lazybox.close()