config/routes.rb
Rails.application.routes.draw do
  
  resources :contactos

  resources :lugar_nacimientos

  resources :roles

  devise_for :users
  resources :estado_civils

  resources :departamentos

  resources :users

  resources :dato_estudiantes do
    get :autocomplete_municipio_nombre, :on => :collection
  end

  resources :municipios

  resources :pais

  resources :tipo_documentos

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  
  
  get 'static_pages/usuarios'
  get 'static_pages/registros'
  get 'static_pages/reportes'
  get 'static_pages/configuracion'
  get 'static_pages/consulta'

  
  
  get 'static_pages/olvidaste_password'
 
  get 'static_pages/registrarse'
 
  get 'static_pages/registro_asistencia'

  get 'static_pages/registro_horarios'
 
  get'static_pages/registros_grados'
 
  get'static_pages/registros_grados'

  get'static_pages/reportes_alumnos'

  get'static_pages/reportes_jornadas'
  
  get 'static_pages/reportes_asistencia'
 
  get'static_pages/configuracion_user'

  get'static_pages/configuracion_preferencias'
 
  get'static_pages/agregar_info'
  
  get'static_pages/consultar_usuarios'
  
  get'static_pages/configurar_grupos'
  
  get'static_pages/consultar_alumnos'
  
  get'static_pages/consultar_jornadas'
  
  match '/home', to: 'static_pages#home',  via: 'get'
  match '/help',	to: 'static_pages#help',  via: 'get'
  match '/about',   to: 'static_pages#about',  via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'
  
  match '/usuarios', to: 'static_pages#usuarios',  via: 'get'
  match '/registros', to: 'static_pages#registros',  via: 'get'
  match '/reportes', to: 'static_pages#reportes',  via: 'get'
  match '/configuracion', to: 'static_pages#configuracion',  via: 'get'
  match '/consulta', to: 'static_pages#consulta',  via: 'get'
  
  match '/olvidaste_password', to: 'static_pages#olvidaste_password',  via: 'get'
  match '/registrarse', to: 'static_pages#registrarse',  via: 'get'
  match '/registro_asistencia', to: 'static_pages#registro_asistencia',  via: 'get'
  match '/registro_horarios', to: 'static_pages#registro_horarios',  via: 'get'
  match '/registros_grados', to: 'static_pages#registros_grados',  via: 'get'
  match '/reportes_asistencia', to: 'static_pages#reportes_asistencia',  via: 'get'
  match '/reportes_alumnos', to: 'static_pages#reportes_alumnos',  via: 'get'
  match '/reportes_jornadas', to: 'static_pages#reportes_jornadas',  via: 'get'
  match '/configuracion_user', to: 'static_pages#configuracion_user',  via: 'get'
  match '/configuracion_preferencias', to: 'static_pages#configuracion_preferencias',  via: 'get'
  match '/agregar_info', to: 'static_pages#agregar_info',  via: 'get'
  match '/consultar_usuarios', to: 'static_pages#consultar_usuarios',  via: 'get'
  match '/consultar_jornadas', to: 'static_pages#consultar_jornadas',  via: 'get'
  match '/consultar_configuracion', to: 'static_pages#consultar_configuracion',  via: 'get'
  match '/consultar_alumnos', to: 'static_pages#consultar_alumnos',  via: 'get'
  match '/configurar_grupos', to: 'static_pages#configurar_grupos',  via: 'get'
  match '/ver', to: 'static_pages#ver',  via: 'get'
  match '/v2', to: 'static_pages#v2',  via: 'get'
  match '/v3', to: 'static_pages#v3',  via: 'get'
  match '/pais', to: 'static_pages#pais',  via: 'get'
 

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer small">
    
    <div class="col-xs-4">
        <strong>Información</strong></br>
        
            <address>
                <br>
            Administradores del Sistema</br>
            Más acerca del Sistema de Asistencia escolar</br>
            Fuentes de información del Sistema</br>
            Indicador Multidimensional de la Calidad Educativa</br>
            Utilidad del Sistema</br>
            </address>
       
    </div>

    <div class="col-xs-4">
       <address>
            <strong>Contacto</strong></br>
            <br>
            Institucion Educativa Jose Acevedo y Gomez</br>
            Secretaría de Educación de Medellín</br>
            Carrera. 8 Sur # 52C - 20 San Rafael, Guayabal</br>
            Tel&eacute;fono: <strong>(57+4) 2552996 - 3612145 - 3617065</strong></br>
            Web: <strong><a href="http://www.iejoseacevedoygomez.edu.co/">www.iejoseacevedoygomez.edu.co/</a></strong></br>
            Medellín, Antioquia, Colombia
        </address>
    </div>
    
     <div class="col-xs-4">
        <ul class="list-unstyled-1">
          <li><%= link_to "Acerca",   about_path %></li>
          <li><%= link_to "Contacto", contact_path %></li>
          <li><%= link_to "Ayuda",   help_path %></li>
        </ul>
    </div>

<div class="text-center">
  <p>
   &copy 2015 Software diseñado y elaborado Softec, Medellín-Colombia. Derechos reservados.
  </P>
</div>
    
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top" id="nav1">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a><%= link_to (image_tag('softec.png')), class: "imagen-header" %></a>
    
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        
        
        
         <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              
              <li>
               <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                <span class="glyphicon glyphicon-home"></span> Home<span class="caret"></span>
              </a>
              </li>
              <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="/static_pages/registros" aria-expanded="true">
               <span class="glyphicon glyphicon-pencil"></span> Registros<span class="caret"></span>
              </a>
            <ul class="dropdown-menu">
                <li><a href="/static_pages/registro_asistencia"> Registrar Asistencia</a></li>
                <li><a href="/static_pages/registro_horarios"> Registrar Horarios</a></li>
                <li><a href="/static_pages/registros_grados"> Registrar Grados</a></li>
            </ul>
        </li>
        
        <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
              <span class="glyphicon glyphicon-wrench"></span> Reportes<span class="caret"></span>
              </a>
            <ul class="dropdown-menu">
                <li><a href="/static_pages/reportes_asistencia">Reportes Asistencia</a></li>
                <li><a href="/static_pages/reportes_alumnos">Reportes Alumnos</a></li>
                <li><a href="/static_pages/reportes_jornadas"> Jornadas</a></li>
            </ul>
        </li>
        
        <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                <span class="glyphicon glyphicon-cog"></span> Configuracion<span class="caret"></span>
              </a>
            <ul class="dropdown-menu">
                <li><a href="/static_pages/configuracion_user">Configurar usuarios</a></li>
                <li><a href="/static_pages/configuracion_preferencias"> Configurar preferencias</a></li>
                <li><a href="/static_pages/agregar_info"> Agregar informacion</a></li>
                <li><a href="/static_pages/configurar_grupos"> Configurar grados</a></li>
            </ul>
        </li>
        
          <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                <span class="glyphicon glyphicon-eye-open"></span> Consultar<span class="caret"></span>
              </a>
            <ul class="dropdown-menu">
                <li><a href="/static_pages/consultar_usuarios"> Consultar usuarios</a></li>
                <li><a href="/static_pages/consultar_alumnos">  Consultar alumnos</a></li>
                <li><a href="/static_pages/consultar_jornadas">Consultar jornadas</a></li>
            </ul>
        </li>
              
          <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                <span class="glyphicon glyphicon-briefcase"></span> Admin<span class="caret"></span>
              </a>            
              <ul class="dropdown-menu">
                <li><%= link_to "Usuarios", users_path %></li>
                <li><%= link_to "Roles", roles_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Administracion provincias</li>
                <li><%= link_to "Paises", pais_path %></li>
                <li><%= link_to "Departamentos", departamentos_path %></li>
                <li><%= link_to "Municipios", municipios_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Administracion estudiantes</li>
                <li><%= link_to "Informacion alumlunos", dato_estudiantes_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Administracion identificacion</li>
                <li><%= link_to "Documentos de identificacion", tipo_documentos_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Estado civil", estado_civils_path %></li>
                
            </ul>
        </li>
              <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true"><%= current_user.email %></a>
                
                <ul class="dropdown-menu">
                  <li><%= link_to 'Editar perfil', edit_user_registration_path %></li> 
                  <li><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete  %></li>
               </ul>
              </li>
               
            <% else %>
              
              <li><%= link_to "Inicio", home_path %></li>
              <li><%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link', class:"btn btn-link btn-xs"  %></li>
              <li><%= link_to "Inicar sesión", new_user_session_path, :class => 'navbar-link', class:"btn btn-link btn-xs"  %></li>
               
           
            <% end %>
        
      
        
        
    
    
      </ul>
      
      
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Softec" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Proyecto Softec" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" type="image/x-icon" href="https://lh5.ggpht.com/eT9hFpMYqwgNeEJOjeZK09fpnpOa4HtbHGwBdkN5ARIhZr2mruQUx5icM8gKjGUr34LegKA=s16" />
    <script src="/softec/app/assets/javascripts/barra.js"></script>
    <link href="/softec/app/assets/stylesheet/barra.css" rel="stylesheet" />
    
  </head>
  <body>
    <header>
  	<%= render 'layouts/navigation' %>
  	  	<%= render 'layouts/navigation_links' %>
    </header>
    <main role="main" class="container">
   	<div class="row">
        	<div class="col-lg-12">
          	<%= render 'layouts/messages' %>
          	<%= yield %>
       	</div>
   	</div>

   	<%= render 'layouts/footer' %>
    </main>
    <%= render_lazybox %> 
  </body>
</html>